### ISSUE TITLE
ElasticSearch not running on 9200 - tag 4.5.4

### ISSUE THREAD

**Issue by bizmate** [willdurand/docker-elk#27]
Given I run 'docker-compose up -d'
When I open kibana on localhost:8080
Then I see error 'Unable to connect to Elasticsearch at http://localhost:9200 .'

I have tried to curl localhost:9200 after docker-compose exec elk bash. But it not responding. 
Anything I am missing? Going to see if I can find the yml config for elastic

Sample docker compose
```
elk:
    image: willdurand/elk:kibana-4.5.4
    ports:
        - "8080:80"
    volumes:
        - ./config:/etc/logstash
   volumes_from:
       - dataelk

dataelk:
    image: busybox
    volumes:
        - /data
```
