### ISSUE TITLE
Logstash configuration file

### ISSUE THREAD

**Issue by AndreaPivetta** [willdurand/docker-elk#28]
What is the minimum configuration I need to use this image?
I'm trying to send logs to logstash by using a custom winston transport (https://github.com/jaakkos/winston-logstash).

In the README I read "Your logstash configuration directory MUST contain at least one logstash configuration file" but by configuration file you mean the one in which I specify `input, output, filter`?

**Comment by willdurand** [comment]
Hi, here is a project that I used as demo: https://github.com/willdurand/gitlab-elk-demo. Not sure it still works well, but at least you can look into the `logstash` directory.

**Comment by AndreaPivetta** [comment]
I'm using `kibana-5.x`, and if I mount a directory with one file, `logstash.conf`, with:
```
 input {
    # Sample input over TCP
    tcp { port => 28777 type=>"sample" }
  }
  output {
    stdout { debug => true }
  }

  filter {
    json {
      source => "message"
    }
  }
```

I get `ERROR: No configuration file was specified. Perhaps you forgot to provide the '-f yourlogstash.conf' flag?`

My docker-compose file:
```
app:
  build: .
  volumes:
    - ./:/opt/app
  ports:
    - 3200:3200
  links:
    - elk
    - mongo
    - cache
mongo:
  image: mongo:3.4
  ports:
    - 27017:27017
cache:
  image: redis:3
  ports:
    - 7379:6379
elk:
  image: willdurand/elk:kibana-5.x
  ports:
    - 8080:80
  volumes:
    - ./logstash:/etc/logstash
```
